server.port: 7009
logging:
  level:
    root: INFO
    de.hf.myfinance: DEBUG
app:
  mfinstruments:
    host: localhost
    port: 7001
  mftransactions:
    host: localhost
    port: 7003
  mfmarketdata:
    host: localhost
    port: 7004
  mfvaluation:
    host: localhost
    port: 7002

springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: de.hf.myfinance
  pathsToMatch: /**

api:
  common:
    version: 1.0.0
    title: CompositeApi
    description: the composition of alle myfinance APIs

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.validateInstrumentRequest-out-0:
    destination: validateInstrumentRequest
    producer:
      required-groups: validateInstrumentauditGroup
  bindings.validateTransactionRequest-out-0:
    destination: validateTransactionRequest
    producer:
      required-groups: validateTransactionRequestAuditGroup
  bindings.validateRecurrentTransactionRequest-out-0:
    destination: validateRecurrentTransactionRequest
    producer:
      required-groups: validateRecurrentTransactionRequestAuditGroup
  bindings.processRecurrentTransaction-out-0:
    destination: processRecurrentTransaction
    producer:
      required-groups: processRecurrentTransactionAuditGroup
  bindings.loadNewMarketData-out-0:
    destination: loadNewMarketData
    producer:
      required-groups: loadNewMarketDataAuditGroup
  bindings.recurrentTransactionApproved-out-0:
    destination: recurrentTransactionApproved
    producer:
      required-groups: recurrentTransactionApprovedAuditGroup

spring.rabbitmq:
  host: 192.168.100.73
  port: 30021
  username: user
  password: vulkan
