server.port: 7009
server.host: localhost
logging:
  level:
    root: DEBUG
    de.hf.myfinance: DEBUG
app:
  mfinstruments:
    host: ${server.host}
    port: 7001
  mftransactions:
    host: ${server.host}
    port: 7002
  mfmarketdata:
    host: ${server.host}
    port: 7003
  mfvaluation:
    host: ${server.host}
    port: 7004

springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: de.hf.myfinance
  pathsToMatch: /**

api:
  common:
    version: 1.0.0
    title: CompositeApi
    description: the composition of alle myfinance APIs

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.validateInstrumentRequest-out-0:
    destination: validateInstrumentRequest
    producer:
      required-groups: validateInstrumentauditGroup
  bindings.validateTransactionRequest-out-0:
    destination: validateTransactionRequest
    producer:
      required-groups: validateTransactionRequestAuditGroup
  bindings.validateRecurrentTransactionRequest-out-0:
    destination: validateRecurrentTransactionRequest
    producer:
      required-groups: validateRecurrentTransactionRequestAuditGroup
  bindings.processRecurrentTransactions-out-0:
    destination: processRecurrentTransactions
    producer:
      required-groups: processRecurrentTransactionsAuditGroup
  bindings.loadNewMarketData-out-0:
    destination: loadNewMarketData
    producer:
      required-groups: loadNewMarketDataAuditGroup
  bindings.recurrentTransactionApproved-out-0:
    destination: recurrentTransactionApproved
    producer:
      required-groups: recurrentTransactionApprovedAuditGroup

spring.rabbitmq:
  host: ${server.host}
  port: 30021
  username: user
  password: vulkan

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:30024/realms/myfinance
          jwk-set-uri: http://localhost:30024/realms/myfinance/protocol/openid-connect/certs