server.port: 7005
logging:
  level:
    root: INFO
    de.hf.myfinance: DEBUG
app:
  mfinstruments:
    host: localhost
    port: 7001

springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: de.hf.myfinance
  pathsToMatch: /**

api:
  common:
    version: 1.0.0
    title: CompositeApi
    description: the composition of alle myfinance APIs

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.instruments-out-0:
    destination: instruments
    producer:
      required-groups: auditGroup

spring.rabbitmq:
  host: 192.168.100.73
  port: 30021
  username: user
  password: vulkan

---
spring.config.activate.on-profile: k8n

app:
  mfinstruments:
    host: mfinstruments
    port: 30024